name: App build
on: push

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Making xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: xCode Build
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: MacSleep.xcodeproj
          scheme: MacSleep
          destination: platform=macOS
          action: build
        
