name: App build
on: push

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - uses: mxcl/xcodebuild@v1
        with:
          action: build
