name: App build
on: push

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: xCode Build
        uses: mxcl/xcodebuild@v1
        with:
          action: build
        
